namespace MinecraftPiApi;
public struct Block(int id, int data = 0)
{
    public int Id { get; set; } = id;
    public int Data { get; set; } = data;
}

public enum BlockId
{
    Air = 0,
    Stone = 1,
    Grass = 2,
    Dirt = 3,
    Cobblestone = 4,
    WoodPlanks = 5,
    Sapling = 6,
    Bedrock = 7,
    WaterFlowing = 8,
    WaterStationary = 9,
    LavaFlowing = 10,
    LavaStationary = 11,
    Sand = 12,
    Gravel = 13,
    GoldOre = 14,
    IronOre = 15,
    CoalOre = 16,
    Wood = 17,
    Leaves = 18,
    Glass = 20,
    LapisLazuliOre = 21,
    LapisLazuliBlock = 22,
    Sandstone = 24,
    Bed = 26,
    Cobweb = 30,
    GrassTall = 31,
    Wool = 35,
    FlowerYellow = 37,
    FlowerCyan = 38,
    MushroomBrown = 39,
    MushroomRed = 40,
    GoldBlock = 41,
    IronBlock = 42,
    StoneSlabDouble = 43,
    StoneSlab = 44,
    BrickBlock = 45,
    Tnt = 46,
    Bookshelf = 47,
    MossStone = 48,
    Obsidian = 49,
    Torch = 50,
    Fire = 51,
    StairsWood = 53,
    Chest = 54,
    DiamondOre = 56,
    DiamondBlock = 57,
    CraftingTable = 58,
    Farmland = 60,
    FurnaceInactive = 61,
    FurnaceActive = 62,
    DoorWood = 64,
    Ladder = 65,
    StairsCobblestone = 67,
    DoorIron = 71,
    RedstoneOre = 73,
    Snow = 78,
    Ice = 79,
    SnowBlock = 80,
    Cactus = 81,
    Clay = 82,
    SugarCane = 83,
    Fence = 85,
    GlowstoneBlock = 89,
    BedrockInvisible = 95,
    StoneBrick = 98,
    GlassPane = 102,
    Melon = 103,
    FenceGate = 107,
    GlowingObsidian = 246,
    NetherReactorCore = 247
}

// For block data values, visit https://www.stuffaboutcode.com/p/minecraft-api-reference.html